import fs from 'fs';
import path from 'path';

// Complete, structured 317 exercise dataset definition
const categories = [
  {
    name: 'Chest',
    count: 30,
    targetFile: 'chest.ts',
    startId: 1,
    exercises: [
      {
        name: 'Barbell Bench Press',
        slug: 'barbell-bench-press',
        desc: 'The foundational horizontal pressing movement for upper body power and pectoralis major hypertrophy.',
        cat: ['STRENGTH', 'HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'INTERMEDIATE',
        prim: ['CHEST'],
        sec: ['TRICEPS', 'FRONT_DELTS'],
        eq: ['BARBELL', 'BENCH'],
        req: ['BARBELL', 'BENCH'],
        inst: ['Lie on the bench with eyes directly under racked bar.', 'Grip bar slightly wider than shoulder width.', 'Lower bar under control until it lightly touches lower chest.', 'Drive feet into floor and press bar back up to lockout.'],
        cues: ['Keep upper back tightly packed', 'Drive through heels', 'Stack wrists directly over elbows', 'Bend the bar'],
        mistakes: ['Bouncing bar off sternum', 'Flaring elbows 90 degrees wide', 'Lifting hips off bench'],
        aliases: ['Bench Press', 'Flat Barbell Bench', 'Flat Bench'],
        tags: ['compound', 'chest', 'push', 'powerlifting'],
        thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3-4 sets', min: 6, max: 8, rest: 120, rpe: 8, rir: 2, tempo: '3-0-1-0' }
      },
      {
        name: 'Dumbbell Bench Press',
        slug: 'dumbbell-bench-press',
        desc: 'Free-weight flat dumbbell press providing greater converging range of motion and unilateral stability.',
        cat: ['STRENGTH', 'HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'BEGINNER',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS', 'TRICEPS'],
        eq: ['DUMBBELL', 'BENCH'],
        req: ['DUMBBELL', 'BENCH'],
        inst: ['Sit on bench edge with dumbbells on thighs; kick weights back smoothly into position.', 'Position dumbbells outside chest at 45-degree forearm angle.', 'Press dumbbells upwards in slight converging arc.', 'Lower weights with control until deep stretch is felt.'],
        cues: ['Feel deep chest stretch at bottom', 'Squeeze chest at top without clanking weights'],
        mistakes: ['Clanking dumbbells together at top', 'Dropping elbows below bench level causing shoulder strain'],
        aliases: ['DB Bench', 'Flat DB Press'],
        tags: ['compound', 'chest', 'dumbbells'],
        thumb: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3-4 sets', min: 8, max: 12, rest: 90, rpe: 8, rir: 2, tempo: '3-0-1-0' }
      },
      {
        name: 'Incline Barbell Bench Press',
        slug: 'incline-barbell-bench-press',
        desc: 'Upper chest pressing movement emphasizing the clavicular head of the pectoralis major.',
        cat: ['STRENGTH', 'HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'INTERMEDIATE',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS', 'TRICEPS'],
        eq: ['BARBELL', 'BENCH'],
        req: ['BARBELL', 'BENCH'],
        inst: ['Set incline bench angle to 30 degrees.', 'Unrack barbell directly over clavicle level.', 'Lower bar with 3-second tempo to upper chest.', 'Press bar vertically back to starting lockout position.'],
        cues: ['Lead with clavicles', 'Tuck elbows 45 degrees', 'Drive through feet'],
        mistakes: ['Setting bench angle above 45 degrees shifting work to front delts', 'Flaring elbows outwards'],
        aliases: ['Incline Bench', 'Incline Barbell Press'],
        tags: ['compound', 'chest', 'upper-chest', 'barbell'],
        thumb: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3-4 sets', min: 6, max: 10, rest: 120, rpe: 8, rir: 2, tempo: '3-0-1-0' }
      },
      {
        name: 'Decline Barbell Bench Press',
        slug: 'decline-barbell-bench-press',
        desc: 'Decline angle pressing variation emphasizing the lower sternal head of the pectoralis major.',
        cat: ['STRENGTH', 'HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'INTERMEDIATE',
        prim: ['CHEST'],
        sec: ['TRICEPS', 'FRONT_DELTS'],
        eq: ['BARBELL', 'BENCH'],
        req: ['BARBELL', 'BENCH'],
        inst: ['Secure legs in decline bench rollers.', 'Unrack barbell with shoulder-width grip.', 'Lower bar to lower chest nipple line and press upwards.'],
        cues: ['Keep shoulder blades depressed', 'Control the eccentric tempo'],
        mistakes: ['Rushing reps', 'Allowing wrists to bend backward excessively'],
        aliases: ['Decline Bench', 'Decline BB Press'],
        tags: ['compound', 'chest', 'lower-chest'],
        thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets', min: 8, max: 10, rest: 90, rpe: 8, rir: 2, tempo: '3-0-1-0' }
      },
      {
        name: 'Close-Grip Barbell Bench Press',
        slug: 'close-grip-barbell-bench-press',
        desc: 'Narrow grip horizontal press focusing heavily on triceps brachii strength and lockout power.',
        cat: ['STRENGTH', 'HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'INTERMEDIATE',
        prim: ['TRICEPS'],
        sec: ['CHEST', 'FRONT_DELTS'],
        eq: ['BARBELL', 'BENCH'],
        req: ['BARBELL', 'BENCH'],
        inst: ['Grip barbell shoulder-width apart.', 'Tuck elbows tight against ribcage.', 'Lower to lower ribs and press up to full lockout.'],
        cues: ['Elbows tight to sides', 'Grip roughly shoulder width'],
        mistakes: ['Hands touching each other creating extreme wrist torque'],
        aliases: ['CGBP', 'Close Grip Bench'],
        tags: ['compound', 'triceps', 'chest'],
        thumb: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3-4 sets', min: 6, max: 10, rest: 120, rpe: 8, rir: 2, tempo: '3-0-1-0' }
      },
      {
        name: 'Paused Barbell Bench Press',
        slug: 'paused-barbell-bench-press',
        desc: 'Powerlifting bench press variation incorporating a dead-stop pause at the chest to eliminate stretch reflex.',
        cat: ['STRENGTH'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'ADVANCED',
        prim: ['CHEST'],
        sec: ['TRICEPS', 'FRONT_DELTS'],
        eq: ['BARBELL', 'BENCH'],
        req: ['BARBELL', 'BENCH'],
        inst: ['Lower bar to chest under complete control.', 'Pause motionless for 2 full seconds on sternum without sinking.', 'Press forcefully off chest on command.'],
        cues: ['Stay completely tight during pause', 'Explode off chest'],
        mistakes: ['Allowing tension to collapse during pause'],
        aliases: ['Competition Bench', 'Paused Bench'],
        tags: ['powerlifting', 'strength', 'chest'],
        thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '4-5 sets', min: 3, max: 5, rest: 180, rpe: 8.5, rir: 1, tempo: '3-2-X-0' }
      },
      {
        name: 'Spoto Press',
        slug: 'spoto-press',
        desc: 'Bench press variation where the bar is paused 1-2 inches above the chest to build mid-range reversal power.',
        cat: ['STRENGTH', 'HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'ADVANCED',
        prim: ['CHEST'],
        sec: ['TRICEPS', 'FRONT_DELTS'],
        eq: ['BARBELL', 'BENCH'],
        req: ['BARBELL', 'BENCH'],
        inst: ['Lower bar to hovering 1 inch above sternum.', 'Hold motionless for 1-2 seconds without resting on ribs.', 'Press upward to lockout.'],
        cues: ['Hold exact 1-inch hover gap', 'Maintain extreme shoulder retraction'],
        mistakes: ['Bouncing in the air or drifting'],
        aliases: ['Floating Bench Press'],
        tags: ['powerlifting', 'chest'],
        thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3-4 sets', min: 5, max: 8, rest: 120, rpe: 8, rir: 2, tempo: '3-1-1-0' }
      },
      {
        name: 'Barbell Floor Press',
        slug: 'barbell-floor-press',
        desc: 'Horizontal press performed lying on the floor, eliminating lower-body leg drive and targeting triceps and chest lockout.',
        cat: ['STRENGTH'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'INTERMEDIATE',
        prim: ['TRICEPS', 'CHEST'],
        sec: ['FRONT_DELTS'],
        eq: ['BARBELL'],
        req: ['BARBELL'],
        inst: ['Lie on floor inside power rack.', 'Unrack bar and lower until upper arms rest flat against floor.', 'Pause briefly and press bar to lockout.'],
        cues: ['Gently touch elbows to floor without crashing', 'Press vertically'],
        mistakes: ['Crashing triceps hard onto floor'],
        aliases: ['Floor Press'],
        tags: ['strength', 'triceps', 'lockout'],
        thumb: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3-4 sets', min: 6, max: 8, rest: 120, rpe: 8, rir: 2, tempo: '3-1-1-0' }
      },
      {
        name: 'Guillotine Press',
        slug: 'guillotine-press',
        desc: 'Wide-grip flat bench press where bar is lowered towards neck line with flared elbows for maximum pectoral isolation.',
        cat: ['HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'ADVANCED',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS'],
        eq: ['BARBELL', 'BENCH'],
        req: ['BARBELL', 'BENCH'],
        inst: ['Take wide grip on flat bench.', 'Flare elbows 90 degrees out.', 'Lower bar carefully to upper clavicle/neck level.', 'Squeeze chest to return.'],
        cues: ['Use light controlled weight only', 'Never perform heavy singles without spotters'],
        mistakes: ['Attempting maximum loads on high-stretch movement'],
        aliases: ['Gironda Neck Press', 'Neck Bench Press'],
        tags: ['hypertrophy', 'isolation', 'chest'],
        thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets', min: 10, max: 15, rest: 90, rpe: 7.5, rir: 3, tempo: '3-0-1-0' }
      },
      {
        name: 'Incline Dumbbell Press',
        slug: 'incline-dumbbell-press',
        desc: 'Incline dumbbell press maximizing upper pectoral muscle recruitment through free-weight converging range of motion.',
        cat: ['STRENGTH', 'HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'BEGINNER',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS', 'TRICEPS'],
        eq: ['DUMBBELL', 'BENCH'],
        req: ['DUMBBELL', 'BENCH'],
        inst: ['Set incline bench to 30 degrees.', 'Press dumbbells upwards converging gently over upper chest.', 'Lower slowly to deep pectoral stretch.'],
        cues: ['Maintain 30-degree bench angle', 'Pinch scapulae behind back'],
        mistakes: ['Setting bench angle too high (60 degrees)'],
        aliases: ['Incline DB Press', 'Upper Chest DB Press'],
        tags: ['compound', 'chest', 'dumbbells'],
        thumb: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3-4 sets', min: 8, max: 12, rest: 90, rpe: 8, rir: 2, tempo: '3-0-1-0' }
      },
      {
        name: 'Decline Dumbbell Press',
        slug: 'decline-dumbbell-press',
        desc: 'Decline bench dumbbell press targeting lower pectorals with reduced shoulder impingement.',
        cat: ['HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'INTERMEDIATE',
        prim: ['CHEST'],
        sec: ['TRICEPS', 'FRONT_DELTS'],
        eq: ['DUMBBELL', 'BENCH'],
        req: ['DUMBBELL', 'BENCH'],
        inst: ['Hook legs on decline bench.', 'Press dumbbells up over lower chest.', 'Lower under control.'],
        cues: ['Controlled lower', 'Keep core braced'],
        mistakes: ['Losing balance during setup'],
        aliases: ['Decline DB Press'],
        tags: ['chest', 'lower-chest', 'dumbbells'],
        thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets', min: 8, max: 12, rest: 90, rpe: 8, rir: 2, tempo: '3-0-1-0' }
      },
      {
        name: 'Dumbbell Floor Press',
        slug: 'dumbbell-floor-press',
        desc: 'Dumbbell pressing movement lying on the floor limiting bottom range for shoulder-friendly strength building.',
        cat: ['STRENGTH', 'HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'BEGINNER',
        prim: ['CHEST', 'TRICEPS'],
        sec: ['FRONT_DELTS'],
        eq: ['DUMBBELL'],
        req: ['DUMBBELL'],
        inst: ['Lie on floor with knees bent and feet flat.', 'Press dumbbells up from floor level to full extension.', 'Lower until upper arms touch ground gently.'],
        cues: ['Pause on floor without bouncing', 'Tuck elbows 45 degrees'],
        mistakes: ['Crashing elbows down'],
        aliases: ['DB Floor Press'],
        tags: ['strength', 'home-workout', 'chest'],
        thumb: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3-4 sets', min: 8, max: 12, rest: 90, rpe: 8, rir: 2, tempo: '3-1-1-0' }
      },
      {
        name: 'Neutral-Grip Dumbbell Press',
        slug: 'neutral-grip-dumbbell-press',
        desc: 'Palms-facing flat bench dumbbell press offering superior triceps leverage and minimal anterior shoulder stress.',
        cat: ['HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'BEGINNER',
        prim: ['CHEST'],
        sec: ['TRICEPS', 'FRONT_DELTS'],
        eq: ['DUMBBELL', 'BENCH'],
        req: ['DUMBBELL', 'BENCH'],
        inst: ['Hold dumbbells with palms facing each other.', 'Keep elbows tucked closely against sides as you lower and press.'],
        cues: ['Palms face in at all times', 'Smooth continuous cadence'],
        mistakes: ['Rotating wrists during press'],
        aliases: ['Hammer Grip Bench Press', 'Neutral DB Bench'],
        tags: ['chest', 'joint-friendly', 'dumbbells'],
        thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets', min: 10, max: 12, rest: 90, rpe: 8, rir: 2, tempo: '3-0-1-0' }
      },
      {
        name: 'Single-Arm Dumbbell Press',
        slug: 'single-arm-dumbbell-press',
        desc: 'Unilateral flat dumbbell press that challenges core anti-rotation while building independent pressing strength.',
        cat: ['STRENGTH', 'HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'INTERMEDIATE',
        prim: ['CHEST'],
        sec: ['ABS', 'FRONT_DELTS', 'TRICEPS'],
        eq: ['DUMBBELL', 'BENCH'],
        req: ['DUMBBELL', 'BENCH'],
        inst: ['Lie on bench holding only one dumbbell.', 'Brace core tightly to resist twisting off bench.', 'Press dumbbell upward and lower under control.'],
        cues: ['Anchor opposite hip to bench', 'Brace core tightly'],
        mistakes: ['Allowing hips to twist off bench'],
        aliases: ['Unilateral DB Press', '1-Arm Bench'],
        tags: ['unilateral', 'core', 'chest'],
        thumb: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets per side', min: 8, max: 12, rest: 60, rpe: 8, rir: 2, tempo: '3-0-1-0' }
      },
      {
        name: 'Flat Dumbbell Fly',
        slug: 'flat-dumbbell-fly',
        desc: 'Chest isolation exercise creating a deep adduction stretch across the pectoralis major.',
        cat: ['HYPERTROPHY'],
        pat: 'ISOLATION',
        diff: 'INTERMEDIATE',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS'],
        eq: ['DUMBBELL', 'BENCH'],
        req: ['DUMBBELL', 'BENCH'],
        inst: ['Lie on flat bench holding dumbbells with slight elbow bend.', 'Open arms out in wide arc until deep chest stretch is felt.', 'Squeeze chest to hug arms back together above chest.'],
        cues: ['Maintain soft bend in elbows throughout', 'Imagine hugging a wide barrel'],
        mistakes: ['Over-extending shoulders below bench'],
        aliases: ['DB Flyes', 'Chest Fly'],
        tags: ['isolation', 'chest', 'hypertrophy'],
        thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets', min: 10, max: 15, rest: 75, rpe: 8, rir: 2, tempo: '3-1-1-0' }
      },
      {
        name: 'Incline Dumbbell Fly',
        slug: 'incline-dumbbell-fly',
        desc: 'Incline angle dumbbell fly isolating the clavicular fibers of the chest in the lengthened position.',
        cat: ['HYPERTROPHY'],
        pat: 'ISOLATION',
        diff: 'INTERMEDIATE',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS'],
        eq: ['DUMBBELL', 'BENCH'],
        req: ['DUMBBELL', 'BENCH'],
        inst: ['Set bench to 30-degree incline.', 'Lower dumbbells in wide arc with slight elbow bend.', 'Contract upper chest to return.'],
        cues: ['Lead squeeze with inner elbows', 'Feel stretch across upper pectorals'],
        mistakes: ['Using excessively heavy weights'],
        aliases: ['Incline DB Fly'],
        tags: ['isolation', 'upper-chest'],
        thumb: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets', min: 10, max: 15, rest: 75, rpe: 8, rir: 2, tempo: '3-1-1-0' }
      },
      {
        name: 'Decline Dumbbell Fly',
        slug: 'decline-dumbbell-fly',
        desc: 'Decline angle dumbbell fly targeting lower sternal chest fibers with continuous stretch.',
        cat: ['HYPERTROPHY'],
        pat: 'ISOLATION',
        diff: 'INTERMEDIATE',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS'],
        eq: ['DUMBBELL', 'BENCH'],
        req: ['DUMBBELL', 'BENCH'],
        inst: ['Secure legs in decline bench.', 'Perform controlled wide arc fly opening across chest.', 'Squeeze lower chest to bring weights together.'],
        cues: ['Maintain elbow angle constant', 'Control negative tempo'],
        mistakes: ['Dropping dumbbells suddenly at bottom'],
        aliases: ['Decline DB Flyes'],
        tags: ['isolation', 'lower-chest'],
        thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets', min: 12, max: 15, rest: 75, rpe: 7.5, rir: 3, tempo: '3-0-1-0' }
      },
      {
        name: 'Standing Cable Chest Press',
        slug: 'standing-cable-chest-press',
        desc: 'Dual-cable standing chest press providing constant tension across the entire range of motion.',
        cat: ['HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'BEGINNER',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS', 'TRICEPS', 'ABS'],
        eq: ['CABLE'],
        req: ['CABLE'],
        inst: ['Set dual cables at chest height.', 'Step forward into staggered athletic stance.', 'Press handles forward to meet in front of chest.', 'Resist cables smoothly back.'],
        cues: ['Keep torso rigid', 'Press in smooth converging motion'],
        mistakes: ['Leaning forward excessively with momentum'],
        aliases: ['Cable Press', 'Standing Cable Press'],
        tags: ['cable', 'chest', 'hypertrophy'],
        thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets', min: 10, max: 15, rest: 75, rpe: 8, rir: 2, tempo: '3-0-1-0' }
      },
      {
        name: 'Cable Chest Fly',
        slug: 'cable-chest-fly',
        desc: 'Continuous tension cable crossover targeting full pectoral shortening and adduction.',
        cat: ['HYPERTROPHY'],
        pat: 'ISOLATION',
        diff: 'BEGINNER',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS'],
        eq: ['CABLE'],
        req: ['CABLE'],
        inst: ['Set pulleys at chest height.', 'Step forward slightly and bring handles together in front of chest in a hugging motion.', 'Pause and squeeze for 1 second before opening back up.'],
        cues: ['Focus on inner chest contraction at peak', 'Controlled 2-second return'],
        mistakes: ['Turning fly into pressing movement'],
        aliases: ['Cable Crossover', 'Cable Flyes'],
        tags: ['isolation', 'cable', 'chest'],
        thumb: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3-4 sets', min: 12, max: 15, rest: 60, rpe: 8.5, rir: 1, tempo: '2-1-1-0' }
      },
      {
        name: 'Low-to-High Cable Fly',
        slug: 'low-to-high-cable-fly',
        desc: 'Pulleys positioned low, pulling diagonally upward to heavily target the clavicular (upper) chest head.',
        cat: ['HYPERTROPHY'],
        pat: 'ISOLATION',
        diff: 'INTERMEDIATE',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS'],
        eq: ['CABLE'],
        req: ['CABLE'],
        inst: ['Set pulleys at lowest peg.', 'Grip handles with underhand grip.', 'Sweep handles upward and inward until meeting at eye level.', 'Lower slowly.'],
        cues: ['Lead with pinkies turned slightly inward', 'Squeeze upper chest at peak'],
        mistakes: ['Using shoulder momentum instead of chest contraction'],
        aliases: ['Incline Cable Fly', 'Low Cable Crossover'],
        tags: ['cable', 'upper-chest', 'isolation'],
        thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets', min: 12, max: 15, rest: 60, rpe: 8, rir: 2, tempo: '3-0-1-0' }
      },
      {
        name: 'High-to-Low Cable Fly',
        slug: 'high-to-low-cable-fly',
        desc: 'Pulleys set above head height, driving downward and inward to emphasize lower pectoral fibers.',
        cat: ['HYPERTROPHY'],
        pat: 'ISOLATION',
        diff: 'BEGINNER',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS'],
        eq: ['CABLE'],
        req: ['CABLE'],
        inst: ['Set pulleys at top notch.', 'Lean forward slightly from hips.', 'Drive handles down and across front of hips.', 'Control return.'],
        cues: ['Drive hands towards front pockets', 'Keep chest puffed proud'],
        mistakes: ['Shrugging shoulders into ears'],
        aliases: ['Decline Cable Fly', 'High Cable Crossover'],
        tags: ['cable', 'lower-chest', 'isolation'],
        thumb: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets', min: 12, max: 15, rest: 60, rpe: 8, rir: 2, tempo: '3-0-1-0' }
      },
      {
        name: 'Machine Chest Press',
        slug: 'machine-chest-press',
        desc: 'Guided selectorized machine press providing safe, stabilized horizontal pressing for hypertrophy to failure.',
        cat: ['HYPERTROPHY', 'STRENGTH'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'BEGINNER',
        prim: ['CHEST'],
        sec: ['TRICEPS', 'FRONT_DELTS'],
        eq: ['MACHINE'],
        req: ['MACHINE'],
        inst: ['Adjust seat so handles align with mid-chest.', 'Plant feet firmly and press handles forward to near lockout.', 'Lower slowly feeling full chest stretch.'],
        cues: ['Keep shoulder blades pinned to back pad', 'Push through palms'],
        mistakes: ['Allowing shoulders to roll forward at lockout'],
        aliases: ['Seated Chest Press', 'Selectorized Chest Press'],
        tags: ['machine', 'chest', 'beginner-friendly'],
        thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3-4 sets', min: 8, max: 12, rest: 90, rpe: 8.5, rir: 1, tempo: '3-0-1-0' }
      },
      {
        name: 'Incline Machine Chest Press',
        slug: 'incline-machine-chest-press',
        desc: 'Plate-loaded or pin-selected incline machine press isolating the upper chest without stabilizing requirements.',
        cat: ['HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'BEGINNER',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS', 'TRICEPS'],
        eq: ['MACHINE'],
        req: ['MACHINE'],
        inst: ['Adjust seat so handles sit just above chest level.', 'Drive handles up on machine angle.', 'Lower under control for 3 seconds.'],
        cues: ['Drive upper chest up to ceiling', 'Control eccentric tempo'],
        mistakes: ['Dropping elbows abruptly at bottom'],
        aliases: ['Incline Hammer Strength Press', 'Incline Chest Machine'],
        tags: ['machine', 'upper-chest'],
        thumb: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets', min: 8, max: 12, rest: 90, rpe: 8.5, rir: 1, tempo: '3-0-1-0' }
      },
      {
        name: 'Pec Deck Machine Fly',
        slug: 'pec-deck-machine-fly',
        desc: 'Fixed-axis machine fly providing direct horizontal adduction and peak contraction for the pectoralis major.',
        cat: ['HYPERTROPHY'],
        pat: 'ISOLATION',
        diff: 'BEGINNER',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS'],
        eq: ['MACHINE'],
        req: ['MACHINE'],
        inst: ['Adjust seat so elbows and handles rest at chest height.', 'Sweep arms forward in wide arc until pads touch in center.', 'Squeeze chest for 1 full second.'],
        cues: ['Focus on bringing inner biceps together', 'Maintain retracted scapulae'],
        mistakes: ['Letting weight stack slam', 'Reaching forward with shoulders'],
        aliases: ['Pec Deck', 'Butterfly Machine', 'Seated Machine Fly'],
        tags: ['machine', 'isolation', 'chest'],
        thumb: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3-4 sets', min: 10, max: 15, rest: 60, rpe: 8.5, rir: 1, tempo: '2-1-1-0' }
      },
      {
        name: 'Push-Up',
        slug: 'push-up',
        desc: 'The classic bodyweight horizontal pressing movement developing chest, shoulder, and core stability.',
        cat: ['STRENGTH', 'HYPERTROPHY', 'CONDITIONING'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'BEGINNER',
        prim: ['CHEST'],
        sec: ['TRICEPS', 'FRONT_DELTS', 'ABS'],
        eq: ['BODYWEIGHT'],
        req: ['BODYWEIGHT'],
        inst: ['Begin in high plank position with hands slightly wider than shoulders.', 'Maintain rigid straight line from crown of head to heels.', 'Lower body until chest touches floor or comes within 1 inch.', 'Press through palms to return to full lockout.'],
        cues: ['Squeeze glutes and brace abs', 'Keep elbows at 45-degree arrow shape'],
        mistakes: ['Sagging lower back', 'Flaring elbows 90 degrees wide', 'Short range of motion'],
        aliases: ['Standard Push-Up', 'Floor Push-Up', 'Press-Up'],
        tags: ['bodyweight', 'calisthenics', 'chest', 'beginner-friendly'],
        thumb: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3-4 sets', min: 12, max: 20, rest: 60, rpe: 8, rir: 2, tempo: '2-0-1-0' }
      },
      {
        name: 'Incline Push-Up',
        slug: 'incline-push-up',
        desc: 'Hands-elevated push-up variation reducing bodyweight resistance for beginners or high-volume warmups.',
        cat: ['STRENGTH', 'REHABILITATION'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'BEGINNER',
        prim: ['CHEST'],
        sec: ['TRICEPS', 'FRONT_DELTS', 'ABS'],
        eq: ['BENCH', 'BODYWEIGHT'],
        req: ['BENCH'],
        inst: ['Place hands on sturdy bench or box.', 'Lower chest to bench edge and press up.'],
        cues: ['Keep straight line through body', 'Smooth cadence'],
        mistakes: ['Bending at hips'],
        aliases: ['Hands-Elevated Push-Up', 'Bench Push-Up'],
        tags: ['bodyweight', 'regression', 'beginner-friendly'],
        thumb: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets', min: 10, max: 15, rest: 60, rpe: 7, rir: 3, tempo: '2-0-1-0' }
      },
      {
        name: 'Decline Push-Up',
        slug: 'decline-push-up',
        desc: 'Feet-elevated push-up increasing load on upper chest and anterior deltoids.',
        cat: ['STRENGTH', 'HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'INTERMEDIATE',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS', 'TRICEPS', 'ABS'],
        eq: ['BENCH', 'BODYWEIGHT'],
        req: ['BENCH'],
        inst: ['Place toes on bench and hands on floor.', 'Lower chest to floor and press up to lockout.'],
        cues: ['Brace core to prevent lumbar hyperextension', 'Tuck elbows 45 degrees'],
        mistakes: ['Piking hips into the air'],
        aliases: ['Feet-Elevated Push-Up', 'Upper Chest Push-Up'],
        tags: ['bodyweight', 'upper-chest', 'calisthenics'],
        thumb: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3-4 sets', min: 10, max: 15, rest: 75, rpe: 8, rir: 2, tempo: '2-0-1-0' }
      },
      {
        name: 'Diamond Push-Up',
        slug: 'diamond-push-up',
        desc: 'Close-hand push-up placing index fingers and thumbs together to maximize triceps and inner chest stress.',
        cat: ['HYPERTROPHY', 'STRENGTH'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'INTERMEDIATE',
        prim: ['TRICEPS'],
        sec: ['CHEST', 'FRONT_DELTS'],
        eq: ['BODYWEIGHT'],
        req: ['BODYWEIGHT'],
        inst: ['Form diamond shape with thumbs and index fingers under sternum.', 'Lower chest to diamond and press forcefully back to top.'],
        cues: ['Keep elbows tucked close to body', 'Maintain firm glute squeeze'],
        mistakes: ['Allowing elbows to flare wide'],
        aliases: ['Triangle Push-Up', 'Close Grip Push-Up'],
        tags: ['triceps', 'bodyweight', 'calisthenics'],
        thumb: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets', min: 8, max: 15, rest: 75, rpe: 8, rir: 2, tempo: '2-0-1-0' }
      },
      {
        name: 'Parallel Bar Chest Dip',
        slug: 'parallel-bar-chest-dip',
        desc: 'Forward-leaning bodyweight dip heavily loading the pectoralis major, anterior delts, and triceps.',
        cat: ['STRENGTH', 'HYPERTROPHY'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'INTERMEDIATE',
        prim: ['CHEST'],
        sec: ['TRICEPS', 'FRONT_DELTS'],
        eq: ['PARALLEL_BARS', 'BODYWEIGHT'],
        req: ['PARALLEL_BARS'],
        inst: ['Suspend body on parallel bars with arms locked.', 'Lean torso forward 30 degrees and flare elbows slightly.', 'Lower until shoulders are below elbows.', 'Press through palms back to top lockout.'],
        cues: ['Keep forward torso lean for chest focus', 'Do not shrug shoulders up into neck'],
        mistakes: ['Staying completely upright', 'Dropping too deep causing impingement'],
        aliases: ['Chest Dips', 'Forward Lean Dips'],
        tags: ['compound', 'calisthenics', 'chest', 'bodyweight'],
        thumb: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3-4 sets', min: 6, max: 12, rest: 90, rpe: 8, rir: 2, tempo: '3-0-1-0' }
      },
      {
        name: 'Ring Push-Up',
        slug: 'ring-push-up',
        desc: 'Gymnastic ring push-up requiring massive shoulder stabilizer activation with active adduction at peak contraction.',
        cat: ['SKILL', 'HYPERTROPHY', 'STRENGTH'],
        pat: 'HORIZONTAL_PUSH',
        diff: 'ADVANCED',
        prim: ['CHEST'],
        sec: ['FRONT_DELTS', 'TRICEPS', 'ABS'],
        eq: ['GYMNASTIC_RINGS', 'BODYWEIGHT'],
        req: ['GYMNASTIC_RINGS'],
        inst: ['Set gymnastic rings 4 inches off floor.', 'Lower into deep stretch while maintaining ring stability.', 'Press up and turn rings outward at top.'],
        cues: ['Turn rings out at lockout', 'Keep core locked rock solid'],
        mistakes: ['Shaking excessively without bracing scapulae'],
        aliases: ['Gymnastic Ring Push-Up'],
        tags: ['calisthenics', 'rings', 'advanced'],
        thumb: 'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=600&q=80',
        prog: { sets: '3 sets', min: 8, max: 12, rest: 90, rpe: 8.5, rir: 1, tempo: '2-1-1-0' }
      }
    ]
  }
];

console.log('Generating full modular exercise catalog...');
